In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from data_objects import Fluorophore, get_fluorophore_list
from imaging_model import fast_form_A, fast_form_A_from_photons, fast_form_A_simultaneous
from information_matrix import read_qe, fast_form_q_vec, FIM

In [2]:
wavelength_range = (400,900)
fluorophore_list = get_fluorophore_list(wavelength_range=wavelength_range)
fluorophore_list

In [3]:
illumination_wavelengths = np.array([405, 488, 561, 637]) # numpy array with the wavelength of each illumination
k = np.array([1, 1, 1, 1])                                # numpy array with (photon flux)*(voxel volume) for each illumination wavelength
bin_wavelength_range = wavelength_range                   # length 2 ordered int tuple with first and last wavelengths detected
bin_width = 10                                            # int denoting size of each wavelength bin

In [4]:
params = (illumination_wavelengths, k, bin_wavelength_range, bin_width, fluorophore_list)

In [5]:
A = fast_form_A(*params)
A

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.74253694e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.93924341e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.13017111e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.27270664e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.26254302e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.75163880e+00],
       [0.00000000e+00, 3.94788300e-03, 0.00000000e+00, 4.42164468e+00],
       [0.00000000e+00, 2.57189571e-02, 0.00000000e+00, 3.70660316e+00],
       [0.00000000e+00, 1.48942159e-01, 0.00000000e+00, 3.01868148e+00],
       [0.00000000e+00, 5.56882373e-01, 0.00000000e+00, 2.22054480e+00],
       [0.00000000e+00, 1.19860960e+00, 0.00000000e+00, 1.54824414e+00],
       [0.00000000e+00, 1.25893602e+00, 0.00000000e+00, 1.07961343e+00],
       [0.00000000e+00, 8.16226734e-01, 0.00000000e+00, 7.49754901e-01],
       [0.00000000e+00, 5.91197403e-01, 0.00000000e

In [6]:
simultaneous_params = ([[405], [488], [561], [637]], [[1], [1], [1], [1]], bin_wavelength_range, bin_width, fluorophore_list)
simultaneous_A = fast_form_A_simultaneous(*simultaneous_params)
print(np.max(np.abs(A - simultaneous_A)))

0.0


In [7]:
A_1 = A[0:50, :] + A[50:100, :] + A[100:150, :] + A[150:200, :]
simultaneous_params_2 = ([[405, 488, 561, 637]], [[1,1,1,1]], bin_wavelength_range, bin_width, fluorophore_list)
A_2 = fast_form_A_simultaneous(*simultaneous_params_2)
np.max(np.abs(A_1 - A_2))

0.0

In [8]:
photon_params = (100, illumination_wavelengths, bin_wavelength_range, bin_width, fluorophore_list)

In [9]:
illumination_wavelengths

array([405, 488, 561, 637])

In [10]:
np.sum(A, axis=1).reshape((4,50)).sum(axis=1)

array([34.89103398, 37.69242249, 21.20930376,  3.30672606])

In [11]:
fluorophore_list[0].spectra

wavelength  excitation  emission
400         400      0.0313       0.0
401         401      0.0290       0.0
402         402      0.0267       0.0
403         403      0.0245       0.0
404         404      0.0216       0.0
..          ...         ...       ...
895         895      0.0000       0.0
896         896      0.0000       0.0
897         897      0.0000       0.0
898         898      0.0000       0.0
899         899      0.0000       0.0

[500 rows x 3 columns]

In [12]:
idx = np.arange(8)
excitation_index = idx // 2
excitation_index

array([0, 0, 1, 1, 2, 2, 3, 3], dtype=int32)

In [13]:
(excitation_index == 2) * idx

array([0, 0, 0, 0, 4, 5, 0, 0])