In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from data_objects import Fluorophore, get_fluorophore_list
from imaging_model import fast_form_A, fast_form_A_from_photons
from information_matrix import read_qe, fast_form_q_vec, FIM

In [2]:
wavelength_range = (400,900)
fluorophore_list = get_fluorophore_list(wavelength_range=wavelength_range)
fluorophore_list

In [3]:
illumination_wavelengths = np.array([405, 488, 561, 637]) # numpy array with the wavelength of each illumination
k = np.array([1, 1, 1, 1])                                # numpy array with (photon flux)*(voxel volume) for each illumination wavelength
bin_wavelength_range = wavelength_range                   # length 2 ordered int tuple with first and last wavelengths detected
bin_width = 10                                            # int denoting size of each wavelength bin

In [4]:
params = (illumination_wavelengths, k, bin_wavelength_range, bin_width, fluorophore_list)

In [5]:
A = fast_form_A(*params)
A

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.35714057e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.16754622e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.15334177e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.50190761e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.41356063e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.34084958e-02],
       [0.00000000e+00, 5.87826800e-05, 0.00000000e+00, 8.69214170e-02],
       [0.00000000e+00, 3.82946816e-04, 0.00000000e+00, 7.28650135e-02],
       [0.00000000e+00, 2.21769978e-03, 0.00000000e+00, 5.93417362e-02],
       [0.00000000e+00, 8.29179547e-03, 0.00000000e+00, 4.36518342e-02],
       [0.00000000e+00, 1.78469029e-02, 0.00000000e+00, 3.04356375e-02],
       [0.00000000e+00, 1.87451435e-02, 0.00000000e+00, 2.12232180e-02],
       [0.00000000e+00, 1.21533477e-02, 0.00000000e+00, 1.47388049e-02],
       [0.00000000e+00, 8.80273498e-03, 0.00000000e

In [6]:
photon_params = (illumination_wavelengths, 100, bin_wavelength_range, bin_width, fluorophore_list)
A = fast_form_A_from_photons(*photon_params)

In [7]:
illumination_wavelengths

array([405, 488, 561, 637])

In [8]:
np.sum(A, axis=1).reshape((4,50)).sum(axis=1)

array([100., 100., 100., 100.])